apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\598073\DEVTOOLS\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cassandra
  name: cassandra
spec:
  ports:
    - name: "7000"
      port: 7000
      targetPort: 7000
    - name: "7001"
      port: 7001
      targetPort: 7001
    - name: "7199"
      port: 7199
      targetPort: 7199
    - name: "9042"
      port: 9042
      targetPort: 9042
    - name: "9160"
      port: 9160
      targetPort: 9160
    - name: "9404"
      port: 9404
      targetPort: 9404
  selector:
    io.kompose.service: cassandra
status:
  loadBalancer: {}
