apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\598073\DEVTOOLS\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: janusgraph
  name: janusgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: janusgraph
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\598073\DEVTOOLS\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/janusgraph: "true"
        io.kompose.service: janusgraph
    spec:
      containers:
        - image: registry.us-east-1.dev.internal/gravitylens/janusgraphbuild1-latest@sha256:6b11ccce4b6ab8b937581e0dc7aaa0c419f72480f08256393eabe34d7ac0124d
          name: janusgraph
          ports:
            - containerPort: 8182
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
status: {}
